version: '3'
services:
  neobase-mongodb:
    image: mongo:latest
    container_name: neobase-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: neobase
      MONGO_INITDB_ROOT_PASSWORD: neobase
    volumes:
      - neobase-mongodb-data:/data/db
    networks:
      - neobase-network

  neobase-redis:
    image: redis:latest
    container_name: neobase-redis
    restart: always
    command: >
      redis-server 
      --requirepass default
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --stop-writes-on-bgsave-error no
    ports:
      - 6379:6379
    volumes:
      - neobase-redis-data:/data
    networks:
      - neobase-network

  neobase-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: neobase-backend
    restart: always
    ports:
      - 3000:3000
    environment:
      - IS_DOCKER=${IS_DOCKER}
      - PORT=${PORT}
      - ENVIRONMENT=${ENVIRONMENT} # DEVELOPMENT, PRODUCTION
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN} # Frontend exposed base url
      - MAX_CHATS_PER_USER=${MAX_CHATS_PER_USER} # 0 for trial mode(1 connection), 1 for unlimited
      - NEOBASE_ADMIN_USERNAME=${NEOBASE_ADMIN_USERNAME}
      - NEOBASE_ADMIN_PASSWORD=${NEOBASE_ADMIN_PASSWORD}
      - SCHEMA_ENCRYPTION_KEY=${SCHEMA_ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - USER_JWT_EXPIRATION_MILLISECONDS=${USER_JWT_EXPIRATION_MILLISECONDS}
      - USER_JWT_REFRESH_EXPIRATION_MILLISECONDS=${USER_JWT_REFRESH_EXPIRATION_MILLISECONDS}
      - NEOBASE_MONGODB_URI=${NEOBASE_MONGODB_URI}
      - NEOBASE_MONGODB_NAME=${NEOBASE_MONGODB_NAME}
      - NEOBASE_REDIS_HOST=${NEOBASE_REDIS_HOST}
      - NEOBASE_REDIS_PORT=${NEOBASE_REDIS_PORT}
      - NEOBASE_REDIS_USERNAME=${NEOBASE_REDIS_USERNAME}
      - NEOBASE_REDIS_PASSWORD=${NEOBASE_REDIS_PASSWORD}
      - DEFAULT_LLM_CLIENT=${DEFAULT_LLM_CLIENT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_MAX_COMPLETION_TOKENS=${OPENAI_MAX_COMPLETION_TOKENS}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
      - GEMINI_MAX_COMPLETION_TOKENS=${GEMINI_MAX_COMPLETION_TOKENS}
      - GEMINI_TEMPERATURE=${GEMINI_TEMPERATURE}
    depends_on:
      - neobase-mongodb
      - neobase-redis
    networks:
      - neobase-network

  neobase-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: neobase-client
    environment:
      - VITE_FRONTEND_BASE_URL=${VITE_FRONTEND_BASE_URL} # Frontend exposed base url
      - VITE_API_URL=${VITE_API_URL} # Backend url with /api
      - VITE_ENVIRONMENT=${VITE_ENVIRONMENT} # DEVELOPMENT, PRODUCTION
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - neobase-backend
    networks:
      - neobase-network

  neobase-example-postgres:
    image: postgres:latest
    container_name: neobase-example-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  neobase-example-clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: neobase-example-clickhouse
    restart: always
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - CLICKHOUSE_DB=testdb
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-init:/docker-entrypoint-initdb.d

  neobase-example-mysql:
    image: mysql:latest
    container_name: neobase-example-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  neobase-mongodb-data:
  neobase-redis-data:
  postgres-data:
  clickhouse-data:
  mysql-data:

networks:
  neobase-network:
    driver: bridge
