version: '3'
services:
  neobase-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: neobase-backend
    restart: always
    ports:
      - 3000:3000
    environment:
      - IS_DOCKER=${IS_DOCKER}
      - PORT=${PORT}
      - ENVIRONMENT=${ENVIRONMENT} # DEVELOPMENT, PRODUCTION
      - MAX_CHATS_PER_USER=${MAX_CHATS_PER_USER} # 0 for trial mode(1 connection), 1 for unlimited
      - NEOBASE_ADMIN_USERNAME=${NEOBASE_ADMIN_USERNAME}
      - NEOBASE_ADMIN_PASSWORD=${NEOBASE_ADMIN_PASSWORD}
      - SCHEMA_ENCRYPTION_KEY=${SCHEMA_ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - USER_JWT_EXPIRATION_MILLISECONDS=${USER_JWT_EXPIRATION_MILLISECONDS}
      - USER_JWT_REFRESH_EXPIRATION_MILLISECONDS=${USER_JWT_REFRESH_EXPIRATION_MILLISECONDS}
      - NEOBASE_MONGODB_URI=${NEOBASE_MONGODB_URI}
      - NEOBASE_MONGODB_NAME=${NEOBASE_MONGODB_NAME}
      - NEOBASE_REDIS_HOST=${NEOBASE_REDIS_HOST}
      - NEOBASE_REDIS_PORT=${NEOBASE_REDIS_PORT}
      - NEOBASE_REDIS_USERNAME=${NEOBASE_REDIS_USERNAME}
      - NEOBASE_REDIS_PASSWORD=${NEOBASE_REDIS_PASSWORD}
      - DEFAULT_LLM_CLIENT=${DEFAULT_LLM_CLIENT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_MAX_COMPLETION_TOKENS=${OPENAI_MAX_COMPLETION_TOKENS}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
      - GEMINI_MAX_COMPLETION_TOKENS=${GEMINI_MAX_COMPLETION_TOKENS}
      - GEMINI_TEMPERATURE=${GEMINI_TEMPERATURE}
    depends_on:
      - neobase-mongodb
      - neobase-redis
    networks:
      - neobase-network
networks:
  neobase-network:
    driver: bridge
